controller:
  hostNetwork: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:926412419614:certificate/e13f9426-e452-4670-9f6a-f56b3f346bf1
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: VpcID=vpc-09d44077df9934f96
