controller:
  hostNetwork: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:123456789:certificate/e13f9426-e452-2222-2222-5555555555
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: VpcID=vpc-xxxxxxx
