fullnameOverride: nginx-internal-ingress-nginx
controller:
  admissionWebhooks:
    enabled: false
  enableAnnotationValidations: true
  ingressClassResource:
    name: nginx-controller
    enabled: true
    controllerValue: k8s.io/ingress-nginx-controller
  ingressClassByName: true
  ingressClass: nginx-controller
  image:
    pullPolicy: IfNotPresent
  publishService:
    enabled: true
  metrics:
    enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:631640027723:certificate/915c1e0d-db0a-46d4-9ae1-f5f1bff4a2fc
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
      service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: true
      service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: 300
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "VpcID=vpc-061266de0c42585f5"
    externalTrafficPolicy: Local
    enableHttp: true
    enableHttps: true
    targetPorts:
      http: 80
      https: special
    type: LoadBalancer
  containerPort:
    http: 80
    https: 443
    special: 8000
  config:
    keep-alive: "3600"
    annotations-risk-level: Critical
    proxy-max-temp-file-size: "0"
    ssl-redirect: "false"
    force-ssl-redirect: "false"
    server-tokens: "false"
    server-snippet: |
      listen 8000;
      if ( $server_port = 80 ) {
        return 308 https://$host$request_uri;
      }
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - ingress-nginx
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - nginx-internal
            - key: app.kubernetes.io/component
              operator: In
              values:
              - controller
          topologyKey: kubernetes.io/hostname
  resources:
    limits:
      cpu: 1000m
      memory: 500M
    requests:
      cpu: 500m
      memory: 250Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 8
    targetCPUUtilizationPercentage: 150
    targetMemoryUtilizationPercentage: 150
defaultBackend:
  enabled: true
  image:
    registry: registry.k8s.io
    image: ingress-nginx/nginx-errors
    tag: "v20231208-4c39e6acc"
  replicaCount: 1
